[workspace]
members = [
    "oatie",
    "mercutio-common", 
    "mercutio-wasm",
    "mercutio-server",
    "mercutio-client",
    "simple-ws",
    "tests",
]

[profile.dev]
debug = true

[profile.release]
debug = true
